In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot('nice food', 30)

[28, 11]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(items, vocab_size) for items in reviews]
print(encoded_reviews)

[[28, 11], [15, 10], [26, 10], [6, 21, 3], [29, 28, 25], [17, 11], [2, 28, 28], [25, 1], [25, 22], [22, 19]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[28 11  0]
 [15 10  0]
 [26 10  0]
 [ 6 21  3]
 [29 28 25]
 [17 11  0]
 [ 2 28 28]
 [25  1  0]
 [25 22  0]
 [22 19  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

2021-10-26 22:20:21.267076: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 15)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 16        
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)

2021-10-26 22:22:09.642379: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-10-26 22:22:09.771644: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2394585000 Hz


In [11]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 163ms/step - loss: 0.5975 - accuracy: 1.0000


1.0

In [13]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [14]:
weights[1]

array([ 0.03925607,  0.08063318, -0.03695108,  0.09215611,  0.01880284],
      dtype=float32)

In [15]:
weights[11]

array([-0.01114576, -0.02385757,  0.0593899 ,  0.00509822, -0.06731927],
      dtype=float32)

In [16]:
weights[15]

array([-0.00265962,  0.08477945, -0.0117723 ,  0.05471328,  0.0536311 ],
      dtype=float32)