In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('sonar_dataset.csv', header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [7]:
df.shape

(208, 61)

In [14]:
df.isna().sum().sum()

0

In [15]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [20]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [21]:
X = df.drop([60], axis=1)
y = df[60]

In [24]:
y.sample(5)

90     R
65     R
142    M
146    M
115    M
Name: 60, dtype: object

In [25]:
y = pd.get_dummies(y, drop_first=True)

In [28]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [33]:
X_train.shape, X_test.shape

((156, 60), (52, 60))

In [35]:
import tensorflow as tf
from tensorflow import keras


model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(loss="binary_crossentropy", optimizer='adam', metrics=['accuracy'])

model.fit(X_train, t_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7082 - accuracy: 0.4214
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6895 - accuracy: 0.4901
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6619 - accuracy: 0.5635
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6549 - accuracy: 0.6948
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6140 - accuracy: 0.6627
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6050 - accuracy: 0.7699
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5997 - accuracy: 0.6771
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5431 - accuracy: 0.6870
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4642 - accuracy: 0.8533
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4968 - accuracy: 0.8040
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.0080 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0047 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0053 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 93/100


In [36]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 4ms/step - loss: 1.0322 - accuracy: 0.7692


[1.032164454460144, 0.7692307829856873]

In [39]:
y_pred = model.predict(X_test).reshape(-1)
y_pred

array([5.8615118e-08, 9.9594057e-01, 9.9521422e-01, 6.0015841e-06,
       1.0000000e+00, 9.8803675e-01, 1.8213931e-01, 9.9999940e-01,
       1.8082169e-06, 1.0000000e+00, 8.5506588e-02, 4.0761828e-03,
       2.6035011e-03, 1.8343031e-03, 3.2144696e-02, 3.9921302e-01,
       9.9945748e-01, 3.8529612e-05, 7.6456666e-03, 9.9999452e-01,
       2.9196685e-06, 9.9999976e-01, 1.9199848e-03, 9.9999034e-01,
       1.5226007e-04, 1.9304963e-07, 4.9075195e-01, 7.4422508e-02,
       9.9999517e-01, 6.6829775e-06, 9.5571476e-01, 3.0719508e-07,
       6.5248281e-01, 1.1359751e-03, 9.9978787e-01, 9.9997449e-01,
       9.9998730e-01, 7.4266195e-03, 9.9991721e-01, 6.8140030e-04,
       2.6429713e-02, 8.4884588e-05, 1.4321804e-02, 1.6516447e-04,
       2.8882429e-05, 4.1964650e-04, 8.8309181e-01, 9.9999952e-01,
       1.3744831e-03, 5.8090389e-03, 2.9155254e-02, 8.4340681e-06],
      dtype=float32)

In [41]:
y_pred = np.round(y_pred)
y_pred[:10]

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [42]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [44]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.89      0.80        27
           1       0.84      0.64      0.73        25

    accuracy                           0.77        52
   macro avg       0.78      0.76      0.76        52
weighted avg       0.78      0.77      0.77        52



In [45]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(loss="binary_crossentropy", optimizer='adam', metrics=['accuracy'])

model.fit(X_train, t_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.8310 - accuracy: 0.4796
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7929 - accuracy: 0.5082
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6872 - accuracy: 0.6186
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6344 - accuracy: 0.6683
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7249 - accuracy: 0.4898
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7161 - accuracy: 0.4940
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7270 - accuracy: 0.5151
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7213 - accuracy: 0.4711
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6980 - accuracy: 0.5446
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6760 - accuracy: 0.5566
Epoch 11/

20/20 [==============================] - 0s 3ms/step - loss: 0.3515 - accuracy: 0.8500
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3457 - accuracy: 0.8927
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3657 - accuracy: 0.8675
Epoch 86/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3933 - accuracy: 0.8450
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2813 - accuracy: 0.8781
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3733 - accuracy: 0.8260
Epoch 89/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3468 - accuracy: 0.8311
Epoch 90/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4388 - accuracy: 0.8608
Epoch 91/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3236 - accuracy: 0.8786
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3157 - accuracy: 0.8771
Epoch 93/100


In [46]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.4897 - accuracy: 0.7692


[0.48972681164741516, 0.7692307829856873]

In [47]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

[4.3207407e-04 7.5990194e-01 9.2718399e-01 2.0228535e-02 9.9975252e-01
 9.2526656e-01 3.0951965e-01 9.9984550e-01 2.1981806e-02 9.9981785e-01]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [48]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.93      0.81        27
           1       0.88      0.60      0.71        25

    accuracy                           0.77        52
   macro avg       0.80      0.76      0.76        52
weighted avg       0.80      0.77      0.76        52

